title: Yixin Wang # your name (or website title) here
logo: "/images/wangyixin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Grow passion for engineering from the previous experience, and take action to reach my goal. 
 Currently, I am seeking for entry-level software engineer role.
  <br><br>
  Proficient in Python, C, HTML, SQL, CSS, JavaScript, Excel VBA, etc.
  <br><br>
  <a href="https://www.linkedin.com/in/yxwang/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-180461602-1 # your Google Analytics tracking ID here
